### ISSUE TITLE
Installation on RHEL 7.4 fails

### ISSUE THREAD

**Issue by beevelop** [YanChii/ansible-role-postgres-ha#13]
Executing the role on a RHEL 7.4 system leads to dependency conflicts – something like:
```
Requires dependency: centos-release
```

This is related to the first task of `postgres-ha/tasks/postgresql_sync.yml`. I had a look at the repository and found a related RHEL package, that can be installed more smoothly. Replacing `pgdg-centos` with `pgdg-redhat` did resolve the installation incompatibilities:
```yml
- name: 'import pg{{ postgres_ha_pg_version | replace(".", "") }} repo'
  yum:
    name: 'https://download.postgresql.org/pub/repos/yum/{{ postgres_ha_pg_version }}/redhat/rhel-7-x86_64/pgdg-redhat{{ postgres_ha_pg_version | replace(".", "") }}-{{ postgres_ha_pg_version }}-3.noarch.rpm'
    state: installed
```

Is there a simple way to make this kind of differentiation in this task?
